### ISSUE TITLE
network_betaplot broken?

### ISSUE THREAD

**Issue by dylancraven** [PoisotLab/betalink#5]
# sample code

#create sample networks (igraph objects)
first_g<- graph.data.frame(first_tt, directed=TRUE,vertices=vertt1$Vertices)
E(first_g)$weight<-first_tt$Sum

sec_g<- graph.data.frame(sec_tt, directed=TRUE,vertices=vertt2$Vertices)
E(sec_g)$weight<-sec_tt$Sum

network_betaplot(first_g,sec_g)

#output is

Error: could not find function "network_betaplot"

**Comment by tpoisot** [comment]
This should be solved. Please use devtools to get the latest version:

~~~ R
library(devtools)
install_github("PoisotLab/betalink")
library(betalink)
data(clownfishes)
A = prepare_data(clownfishes)
network_betaplot(A[[1]], A[[2]])
~~~

**Comment by dylancraven** [comment]
Thanks!
